#.travis.yml

language: node_js
node_js:
  - "7.10.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - npm run build:production

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email:
    on_failure: change
    on_success: change
